# Generated by Django 5.2.7 on 2025-10-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_wishlist_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecheck',
            old_name='wishlist_id',
            new_name='watchlist_id',
        ),
    ]
