# Generated by Django 5.2.7 on 2025-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_wishlist_id_pricecheck_watchlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecheck',
            name='target_price',
            field=models.IntegerField(default=0),
        ),
    ]
