# Generated by Django 5.2.7 on 2025-10-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pricecheck_target_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecheck',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='pricecheck',
            old_name='watchlist_id',
            new_name='watchlist',
        ),
    ]
